sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
  - '6'
  - '7'
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm prune
  - sleep 6