version: "{build}"

image: Visual Studio 2017

environment:
  matrix:
    - NODEJS_VERSION: "8"
      BROWSER: firefox
    - NODEJS_VERSION: "10"
      BROWSER: chrome-headless
    - NODEJS_VERSION: "8"
      BROWSER: internet-explorer

cache:
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

install:
  - ps: Install-Product node $env:NODEJS_VERSION
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run test

build: off

branches:
  only:
    - master

matrix:
  fast_finish: true
