version: "{build}"

image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "6"
      browser: chrome
    - nodejs_version: "7"
      browser: firefox
    - nodejs_version: "8"
      browser: chrome-headless
    - nodejs_version: "8"
      browser: phantomjs

cache:
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - BROWSER=$env:browser
  - npm test

build: off
