version: "{build}"

image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"

cache:
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

install:
  - node --version
  - npm --version
  - nvm --version
  - npm install

test_script:
  - npm test

build: off
