name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-typecheck:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm ci
      - name: Check code style
        run: npm run lint
      - name: Check types
        run: npm run typecheck
  test:
    timeout-minutes: 15
    needs: lint-typecheck
    strategy:
      fail-fast: false
      matrix:
        environment: [Firefox, Chrome, Internet_Explorer, BrowserStack_Safari]
        include:
          - environment: Firefox
            os: 'ubuntu-latest'
            nodeVersion: '8'
            browser: 'firefox'
            headless: 'true'
          - environment: Chrome
            os: 'macos-latest'
            nodeVersion: '12'
            browser: 'chrome'
          - environment: Internet_Explorer
            os: 'windows-latest'
            nodeVersion: '12'
            browser: 'internet-explorer'
          - environment: BrowserStack_Safari
            os: 'ubuntu-latest'
            nodeVersion: '12'
            browser: 'safari'
            browserStack: 'true'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.nodeVersion }}
      - name: Install dependencies
        run: npm ci
        env:
          CHROMEDRIVER_VERSION: '79.0.3945.36'
      - name: Run tests
        run: npm run test:coverage
        env:
          BROWSER: ${{ matrix.browser }}
          HEADLESS: ${{ matrix.headless }}
          BROWSERSTACK: ${{ matrix.browserStack }}
          BROWSERSTACK_USERNAME: ${{ secrets.browserStackUsername }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.browserStackAccessKey }}
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ${{ matrix.environment }}
          path: screenshots
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.codeCovUploadToken }} #required
